export { createDashboardUI, DashboardUIKey, useDashboardUI, type DashboardUIOptions } from './plugin/createDashboardUI'
export { useTheme } from './composables/useTheme'
export type { Size, ColorKey } from './types/common'
export * from './types/theme'
export * from './types/button'
export * from './types/icon'
export * from './theme/tokens/index'
export { createColorPalette } from './theme/tokens/types'
export { lightTheme, darkTheme } from './theme/themes'
export { mergeThemes, generateCSSVars, applyTheme, generateUtilityClasses } from './theme/themeEngine'
export { createTheme, createDarkTheme } from './theme/createTheme'
export { iconFactory } from './icons'
// Componentes principales
export { default as VButton } from './components/VButton'
export { default as VIcon } from './components/VIcon'
// Composables y utilidades
export { useUtils } from './composables/utils'
